import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import AuthWrapper from "@/components/main/AuthWrapper";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (

    <html lang="en" className="dark">
      <body className="bg-background text-foreground">
        <AuthWrapper>
          {children}
        </AuthWrapper>
      </body>
    </html>
  );
}
