import type { Metadata } from 'next'
import { ThemeProvider } from 'next-themes'

import './globals.css'
import AuthWrapper from '@/components/main/AuthWrapper'
import { Toaster } from '@/components/ui/toaster'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en' className='dark' suppressHydrationWarning>
			<body className='bg-background text-foreground'>
				<ThemeProvider enableSystem={true} attribute='class'>
					<AuthWrapper>{children}</AuthWrapper>
					<Toaster />
				</ThemeProvider>
			</body>
		</html>
	)
}
