import type { Metadata } from "next";
import "./globals.css";
import AuthWrapper from "@/components/main/AuthWrapper";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body className="bg-background text-foreground">
        {/* <AuthWrapper>{children}</AuthWrapper> */}
        {children}
        <Toaster />
      </body>
    </html>
  );
}
